version: "3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: musicstore
      MYSQL_ROOT_PASSWORD: testpassword
    volumes:
      - mysql-data:/var/lib/mysql
  es:
    image: elasticsearch:7.7.0
    restart: always
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
  api:
    image: 127.0.0.1:5000/musicstore-api
    build: ./service
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
      - es
  ui:
    image: 127.0.0.1:5000/musicstore-ui
    restart: always
    build: ./ui
    depends_on:
      - api
  nginx:
    image: 127.0.0.1:5000/musicstore-nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - ui

volumes:
  mysql-data:  
  es-data: