version: "3"

services:
  ui:
    image: 127.0.0.1:5000/musicstore-ui
    build: ./ui-basic
    ports:
      - 80:80
    depends_on:
      - api
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: musicstore
      MYSQL_ROOT_PASSWORD: testpassword
    volumes:
      - mysql-data:/var/lib/mysql
  es:
    image: elasticsearch:7.7.0
    restart: always
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  api:
    image: 127.0.0.1:5000/musicstore-api
    build: ./service
    restart: always
    ports:
      - 3000:80
    env_file:
      - ./.env
    depends_on:
      - db
      - es

volumes:
  mysql-data:  
  es-data: